import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function addDummyData() {
  try {
    // 1. Need a user to report
    const reporter = await prisma.user.findFirst();
    if (!reporter) {
       console.log("No users found to create a report.");
       return;
    }

    // 2. Need a voice pin to be reported
    const voicePin = await prisma.voicePin.findFirst();
    if (!voicePin) {
       console.log("No voice pins found to be reported.");
       return;
    }

    // 3. Create a Report
    const report = await prisma.report.create({
      data: {
        reason: 'SPAM',
        description: 'This is a test report generated by an admin script.',
        reporterId: reporter.id,
        voicePinId: voicePin.id,
        status: 'PENDING'
      }
    });
    console.log("Created dummy Report:", report);

    // 4. Create an AuditLog for testing
    const auditLog = await prisma.auditLog.create({
      data: {
        action: 'REPORT_CREATED_TEST',
        targetType: 'Report',
        targetId: report.id,
        details: { note: 'Initial test data generation' },
        adminId: reporter.id // Just reusing a user as admin for test
      }
    });

    console.log("Created dummy AuditLog:", auditLog);

  } catch (error) {
    console.error("Error creating test data:", error);
  } finally {
    await prisma.$disconnect();
  }
}

addDummyData();
