
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "DucTri@gmail.com",
    "password": "123456789"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json
  
{
   "username": "DucTri@gmail.com",
    "password": "123456789"
}

### Fetch all todos Get
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0OTk0MDc3LCJleHAiOjE3NTUwODA0Nzd9.Y53HXLU3Ko98NokGsJpFvju5gEjHZfhBLShzE6UHWSc

### Creates a new todo
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0OTk0MDc3LCJleHAiOjE3NTUwODA0Nzd9.Y53HXLU3Ko98NokGsJpFvju5gEjHZfhBLShzE6UHWSc
Content-Type: application/json

{
    "task" : "Finishhh coding the project:>>"
}

### Update a todo PUT /todos/:id (protected)
PUT http://localhost:5003/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0OTkzNTQxLCJleHAiOjE3NTUwNzk5NDF9.LWKeosLQZnvmlK2Srci4Q2kt1pZG6D_XQlsg6Ku0X6Y
Content-Type: application/json

{
    "completed" : 1
}

### Delete a todo PUT /todos/:id (protected)
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU0OTk0MDc3LCJleHAiOjE3NTUwODA0Nzd9.Y53HXLU3Ko98NokGsJpFvju5gEjHZfhBLShzE6UHWSc